                    <!-- The Modal -->
                    <DIV  >
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">¿Usted es?</h4>
                                        <button type="button" class="close" data-dismiss="modal">×</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
<table border="0" width="100%"><tr><td align="center">
										<a href="/vista/registrarEmpresa.php"><img src="/vista/images/empresa.png" style="width:261px;height:193px; alt="empresa"></img></a>
						</td><td align="center">				<h3>Empresa</h3><br><br>
</td></tr><td align="center">
										 

										<a href="/vista/registroInformatico.php"><img src="/vista/images/informatico.png" style="width:261px;height:193px; alt="informatico"></a>
			</td><td align="center">							<h3>Informático</h3>
</td></tr></table>
									</div>
                                </div>
							</div> 
						</div>