                    <!-- The Modal -->
                    <DIV ALIGN=center>
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">¿Usted es?</h4>
                                        <button type="button" class="close" data-dismiss="modal">×</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">

									<a href="/vista/registrarEmpresa.php"><img src="/vista/images/empresa.png" style="width:261px;height:193px; alt="empresa"></img></a>
									<strong>Empresa</strong>

									<br>
									<br>

									<a href="/vista/registroInformatico.php"><img src="/vista/images/informatico.png" style="width:261px;height:193px; alt="informatico"></a>
									<strong>Informático</strong>

									</div>
                                </div>
							</div> 
						</div>